### ISSUE TITLE
OpenShift & fsGroup SecurityContext

### ISSUE THREAD

**Issue by ArthurVardevanyan** [dragonflydb/dragonfly-operator#116]
This change in Operator 0.0.8 causes the pods to not start start due to OpenShift requiring the use of Random UIDs

OpenShift will inject a given fsGroup for a given namespace:
![image](https://github.com/dragonflydb/dragonfly-operator/assets/21159051/76583601-b9e4-489d-ad30-6f4447cffa22)

REF:  
- https://github.com/dragonflydb/dragonfly-operator/pull/98/commits/22040fea90b2bcc40b65fdeabc3fd5e6bfd60039
- https://docs.openshift.com/container-platform/4.13/authentication/managing-security-context-constraints.html

**Comment by Pothulapati** [comment]
Interesting but Dragonfly binary also requires a specific fsGroup to let the binary inside have the required permissions on volumes. Any ideas on what do you think we should do? We could attach that group only when backups are scheduled but this would still cause this problem when there are backups needed.

**Comment by ArthurVardevanyan** [comment]
The random UIDs are per namespace not per pod, I wouldn't expect there to be an issue.

**Comment by Pothulapati** [comment]
So, We are trying to fix this. First, we want to explore how other Operators that also have a fsGroup being set work with Openshift

@ArthurVardevanyan Do you have any ideas on how we should fix this?

**Comment by ArthurVardevanyan** [comment]
Here is an example from the Crunchy Postgres Operator:

In Code:
https://github.com/CrunchyData/postgres-operator/blob/0f8d886f8f2d16b1310255884709e47613a7f115/internal/controller/standalone_pgadmin/pod.go#L357

In Yaml: 
https://github.com/ArthurVardevanyan/HomeLab/blob/production/kubernetes/quay/base/postgres/quay/postgres.yaml#L118

**Comment by ArthurVardevanyan** [comment]
PR: https://github.com/dragonflydb/dragonfly-operator/pull/163

**Comment by Pothulapati** [comment]
#163 merged, hence closing!
