### ISSUE TITLE
Is it production-ready?

### ISSUE THREAD

**Issue by matrix-root** [dragonflydb/dragonfly-operator#130]
Good day dear everyone and thanks for such cool product!
Going to use it in production, but have few questions regarding persistence

> Am I right that snapshot-system is required to have complete robust production-ready setup?
> As I understand - question is yes. At least because it's only option to attach PVC to pods

> And one more question - what schedule stands for? 
> Am I right that persistence-sync will be executed one time per 5 mins (or other time based on cron-schedule)
> So, is it correct that between schedule-triggering I could lost data?

Anyway, thanks for awesome stuff one more time! 🙏

**Comment by Pothulapati** [comment]
Hey @matrix-root, Thanks for raising the issue and all the good words.

> Am I right that snapshot-system is required to have complete robust production-ready setup?

It's not mandatory for caches but its advised. If you have want to have snapshots, The suggested option is PVC's but we also added[ support snapshotting into S3 directly](https://www.dragonflydb.io/docs/managing-dragonfly/operator/snapshot-s3) (which is really good, and I can recommend it). But by default you can always just use the local host node storage for snapshots with the relevant PVC behind.

> And one more question - what schedule stands for?
Am I right that persistence-sync will be executed one time per 5 mins (or other time based on cron-schedule)
So, is it correct that between schedule-triggering I could lost data?

Nope. With schedules you have a more granular control over when you want to backup but whenever a pod terminates irrespective of schedules, They always write into the specified path (S3 or PVC) and then shut down so there is no loss of data if they shutdown correctly but sudden terminations could cause the loss and in which case having a granular schedule helps. 

Hope i answered your questions!
