### ISSUE TITLE
Question about priorityClassName

### ISSUE THREAD

**Issue by steache** [dragonflydb/dragonfly-operator#132]
Hello,

would you be interetested in me adding priorityClassName to the statefulsets managing dragonfly?

We have few fixed/dynamic node pools, so it would be really nice to not only push them a bit by affinity/antiAffinity but also to evict some pods, if these with higher priority need to take their spot. :)

Thank you!

**Comment by Pothulapati** [comment]
Hey @steache,

Sounds like a valid request. Can you raise a PR?

Thanks
