### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by bluegumcity** [dragonflydb/dragonfly-operator#140]
Is there a plan to sync operator releases with dragonfly?

Since its last release, which uses dragonfly 1.12.0, there's been two dragonfly releases (12.1 and 13.0).

**Comment by chakaz** [comment]
We currently do not sync the releases of the operator and Dragonfly, but you can specify `image` as a config: https://www.dragonflydb.io/docs/managing-dragonfly/operator/dragonfly-configuration

**Comment by bluegumcity** [comment]
@chakaz  Ah cheers. Didn't see that one.
