### ISSUE TITLE
add support to pass in a aclfile

### ISSUE THREAD

**Issue by 34fathombelow** [dragonflydb/dragonfly-operator#144]
We have the ability to use the `--aclfile` option as an `arg` but no way to inject this file.   A [secret mounted through a volume](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) would work.  I'm also open to other options.  

Thanks for this awesome project!

**Comment by Pothulapati** [comment]
Thanks @34fathombelow for the kind words! 

Its a valid feature request, and should be straightforward to implement.
