### ISSUE TITLE
Documentation missing new features

### ISSUE THREAD

**Issue by zaphinath** [dragonflydb/dragonfly-operator#162]
The [docs](https://www.dragonflydb.io/docs/managing-dragonfly/operator/dragonfly-configuration) are missing the newest release features such as topologySpreadConstraints, PriorityclassName, nodeSelector field and etc from the 1.1.1 release. Not sure how to add them to the operator docs.

**Comment by Abhra303** [comment]
yep, we have an open issue [here](https://github.com/dragonflydb/documentation/issues/216). Feel free to open a PR :)
