### ISSUE TITLE
Cache reset on rolling updates or if master restarts

### ISSUE THREAD

**Issue by cmergenthaler** [dragonflydb/dragonfly-operator#191]
We have a dragonfly cluster running with 3 replicas, which worked fine so far.
In the last day we have observed to strange behaviors:

1. When doing a rolling update by e.g increasing resource requests, the operator restarts one pod after another (starting with replicas) and chooses a new master. So far so good, but once all pods are up and running again, the cache is being reset instead of synced. 
Number of entries in the cache:
<img width="2537" alt="Bildschirmfoto 2024-05-29 um 14 19 47" src="https://github.com/dragonflydb/dragonfly-operator/assets/377953/1624e0b8-2a44-49aa-b25c-bb6646358b10">

3. When the master restarts at some 
point, the cache is also reset instead of failing over to one of the replicas. Since the master restarts, its cache is empty and the 2 replicas are synced with empty caches as well.
Number of entries in the cache:
<img width="2532" alt="Bildschirmfoto 2024-05-29 um 14 22 32" src="https://github.com/dragonflydb/dragonfly-operator/assets/377953/8eabb6a3-38e0-4a4f-9db8-547b080dd884">

Should these two cases be supported already?

**Comment by Abhra303** [comment]
Hi @cmergenthaler, Thanks for Reporting!

> When doing a rolling update by e.g increasing resource requests, the operator restarts one pod after another (starting with replicas) and chooses a new master. So far so good, but once all pods are up and running again, the cache is being reset instead of synced.

We currently don't have this feature so restarts will loose all the data. But it would be nice enhancement indeed.

> When the master restarts at some point, the cache is also reset instead of failing over to one of the replicas. Since the master restarts, its cache is empty and the 2 replicas are synced with empty caches as well.

We have a open PR for that (#189) , I will push some fixes to the PR. So you can expect this in the next version.

**Comment by cmergenthaler** [comment]
> Hi @cmergenthaler, Thanks for Reporting!
> 
> > When doing a rolling update by e.g increasing resource requests, the operator restarts one pod after another (starting with replicas) and chooses a new master. So far so good, but once all pods are up and running again, the cache is being reset instead of synced.
> 
> We currently don't have this feature so restarts will loose all the data. But it would be nice enhancement indeed.

So whenever we change something on the deployment, our cache is getting reset? Would be nice if the rolling update makes sure that the cache keeps synced over restarting pods.

> 
> > When the master restarts at some point, the cache is also reset instead of failing over to one of the replicas. Since the master restarts, its cache is empty and the 2 replicas are synced with empty caches as well.
> 
> We have a open PR for that (#189) , I will push some fixes to the PR. So you can expect this in the next version.

Good to hear, thanks!

**Comment by Abhra303** [comment]
> > Hi @cmergenthaler, Thanks for Reporting!
> > > When doing a rolling update by e.g increasing resource requests, the operator restarts one pod after another (starting with replicas) and chooses a new master. So far so good, but once all pods are up and running again, the cache is being reset instead of synced.
> > 
> > 
> > We currently don't have this feature so restarts will loose all the data. But it would be nice enhancement indeed.
> 
> So whenever we change something on the deployment, our cache is getting reset? Would be nice if the rolling update makes sure that the cache keeps synced over restarting pods.

Actually, I was wrong here. The operator does handle the syncing of replicas on rolling updates. I think we have a bug here. Will debug more.

**Comment by cmergenthaler** [comment]
> > > Hi @cmergenthaler, Thanks for Reporting!
> > > > When doing a rolling update by e.g increasing resource requests, the operator restarts one pod after another (starting with replicas) and chooses a new master. So far so good, but once all pods are up and running again, the cache is being reset instead of synced.
> > > 
> > > 
> > > We currently don't have this feature so restarts will loose all the data. But it would be nice enhancement indeed.
> > 
> > 
> > So whenever we change something on the deployment, our cache is getting reset? Would be nice if the rolling update makes sure that the cache keeps synced over restarting pods.
> 
> Actually, I was wrong here. The operator does handle the syncing of replicas on rolling updates. I think we have a bug here. Will debug more.

Thanks! I think the problem is if a new pod (which was a replica) gets the master role too early (cache is not fully synced with old cache yet). We have observed that for example we had 20k keys in the cache. After the replicas restarted and the master was restarting, a replica pod became the master but it only contained 1k keys at that time. So 19k keys were not synced yet and therefore got removed from the cache

**Comment by cmergenthaler** [comment]
Seems 1.1.3 has fixed the issue and dragonfly instances are running stable since a couple of weeks now. Closing this
