### ISSUE TITLE
Rollout stuck when there is only a single pod

### ISSUE THREAD

**Issue by denniskorbginski** [dragonflydb/dragonfly-operator#196]
I am encountering an issue in our dev cluster where we are running dragonfly with a single pod only (as in "`spec.replicas` is set to 1"). When the pod spec changes, the operator is unable to update the stateful set. It will produce these logs:

```
INFO	Rolling out new version
INFO	0/0 replicas are in stable state
ERROR	could not get latest replica
```

From what I understand, the issue comes from [this code in the reconciliation loop](https://github.com/dragonflydb/dragonfly-operator/blob/179803b9a9bf1f0cc92f085250659194ffab8491/internal/controller/dragonfly_controller.go#L189-L193). It seems to assume that there is at least one replica that can eventually take over as master, which is not the case when I had only one pod to begin with.

**Comment by Abhra303** [comment]
Thanks for reporting! will fix.
