### ISSUE TITLE
Improve the Helm Chart and operator version management

### ISSUE THREAD

**Issue by Aym3nTN** [dragonflydb/dragonfly-operator#208]
Hey folks,

This initiative aims to improve the version release management process for both the operator and the Helm chart.

I came across [this pull request](https://github.com/dragonflydb/dragonfly-operator/pull/174) by [nujragan93](https://github.com/nujragan93). While the proposed solution might work (with this fix https://github.com/dragonflydb/dragonfly-operator/pull/174#issuecomment-2210430425), I believe there is room for improvement.

Currently, the version management of both components can be simplified by using the same version on both sides. However, this isn't technically the best approach, as changes to the Chart might not always require changes to the Operator logic, this would mean only bumping the Chart version in such cases, and vice versa.

Instead of manually bumping versions, we could leverage the [semantic-release](https://semantic-release.gitbook.io/) tool. It can automatically determine which version to bump to (major, minor, patch) by analyzing commit messages for specific keywords, as detailed in their [documentation](https://semantic-release.gitbook.io/semantic-release#commit-message-format). We've successfully used this tool internally to automate the release of several Terraform modules and Helm Charts, saving us a considerable amount of time.

I'd like to open this discussion to the community and gather your thoughts on this initiative.

**Comment by Abhra303** [comment]
Hi @Aym3nTN, though making operator release and chart release separate is good to have, we prefer to maintain our current manual release workflow for now. Should there be a significant demand for separate releases in the future, we will surely consider this tool.
