### ISSUE TITLE
[Bug] Helm chart update error

### ISSUE THREAD

**Issue by danilrwx** [dragonflydb/dragonfly-operator#220]
#### Error
With default values and flux update failed from 1.1.5

`Warning  UpgradeFailed  100s  helm-controller  Helm upgrade failed for release dragonfly-operator/dragonfly-operator with chart dragonfly-operator@1.1.6+30ca05d11880: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 15: mapping key "app.kubernetes.io/instance" already defined at line 9`
#### Way to reproduce
Run ```helm template -f values.yaml .``` from the root of the chart folder and notice repetitive labels in deployment resource.

#### Places where I found duplicates
1. ClusterRole: release-name-dragonfly-operator-metrics-reader
2. ClusterRole: release-name-dragonfly-operator-proxy-role

**Comment by Abhra303** [comment]
Thanks for reporting! Opened a PR to fix :)

**Comment by xlejakx** [comment]
same problem, same error
