### ISSUE TITLE
Fix controller label on metrics

### ISSUE THREAD

**Issue by applike-ss** [dragonflydb/dragonfly-operator#251]
I just had a look at metrics of the dragonfly controller as i wondered why we weren't alerted by reconcile errors.

What i found was this (on the /metrics endpoint):
```
# HELP controller_runtime_reconcile_errors_total Total number of reconciliation errors per controller
# TYPE controller_runtime_reconcile_errors_total counter
controller_runtime_reconcile_errors_total{controller="dragonfly"} 0
controller_runtime_reconcile_errors_total{controller="pod"} 17
```

Should this be corrected so that the controller `dragonfly` gets the metric values? `pod` seems to be very generic to me. Or is this intended in a way?

**Comment by Pothulapati** [comment]
Thanks @applike-ss for the bug! Yep, Valid and should be fixed. something like dragonfly_pod or something. This is automatically generated by the kube-builder runtime so we might have missed it.
