### ISSUE TITLE
resource: Add a way for the user to set redis password

### ISSUE THREAD

**Issue by Pothulapati** [dragonflydb/dragonfly-operator#50]
Allow users to set a password for their dragonfly instance through a secret.
We should have to use the same secret from the Operator to run commands.

**Comment by laurivosandi** [comment]
Make it possible to specify not only secret name but also the key inside the secret

Better yet have the operator populate the secret with various usable structures including the Redis URI

**Comment by timtorChen** [comment]
How about supporting env and envFrom in Dragonfly CR? 
As setting up environment `DFLY_PASSWORD` is now possible https://github.com/dragonflydb/dragonfly/pull/792.

**Comment by chakaz** [comment]
I can think of 2 ways to specify the password outside of the direct command line arguments
* Use `--flagfile` and set the password there
* Use `--fromenv` (or `--tryfromenv`), which allows specifying certain flags in env variables
For example:
```
FLAGS_requirepass=1234 dragonfly --fromenv=requirepass [...]
```

**Comment by ksingh-scogo** [comment]
👀  much needed feature to use dragonfly that is deployed using operator in production setup

**Comment by tekumara** [comment]
See https://www.dragonflydb.io/docs/managing-dragonfly/operator/authentication

**Comment by chakaz** [comment]
For those interested in setting flags using environment variables, we recently added such support. See [here](https://www.dragonflydb.io/docs/managing-dragonfly/flags) for more details, but tl;dr is use `DFLY_flag` as env var and you should be good to go

**Comment by Pothulapati** [comment]
Closing this as we support this through a secret now: https://www.dragonflydb.io/docs/managing-dragonfly/operator/authentication#password-based-authentication

Also, With `args` filed any extra number of configurations can also be passed.
