### ISSUE TITLE
CRD is duplicated across multiple files

### ISSUE THREAD

**Issue by uhthomas** [dragonflydb/dragonfly-operator#65]
The installation documentation says that two files should be applied, one for the CRDs and one for the actual operator. The operator manifests also include the CRD and so either it shouldn't be there, or the `crd.yaml` is redundant.

https://github.com/dragonflydb/dragonfly-operator/blob/9de38e7c11c4fbb73e509c5921bd1b2c19e13b9d/README.md#L20-L25

https://github.com/dragonflydb/dragonfly-operator/blob/9de38e7c11c4fbb73e509c5921bd1b2c19e13b9d/manifests/crd.yaml#L1-L118

https://github.com/dragonflydb/dragonfly-operator/blob/9de38e7c11c4fbb73e509c5921bd1b2c19e13b9d/manifests/dragonfly-operator.yaml#L13-L131

**Comment by aaronmondal** [comment]
I also just hit this. Seems like the installation instructions are wrong and the operator already contains all the CRDs?

**Comment by Pothulapati** [comment]
Hey @uhthomas and @aaronmondal, Thanks for raising the issue! Yep the Operator installation does have all the things including the CRD! This should not have caused any issues though! I will update the readme to only include the Operator yaml installation.
