### ISSUE TITLE
Prometheus and Grafana Integration

### ISSUE THREAD

**Issue by ionfury** [dragonflydb/dragonfly-operator#72]
It would be great if the operator included or provisioned resources to integrate with Prometheus and Grafana out of the box.  Specifically, creating the following resources would be very helpful:

-  Either `podMonitor` or `serviceMonitors` for downstream dragonfly metrics & the operator itself.
- `PrometheusRule`s to alert on issues with the operator & downstream dragonflies.
- A [`configMap`](https://github.com/grafana/helm-charts/blob/eb55960453f49814d3234fd4417ffb2d5b127b80/charts/grafana/values.yaml#LL861C11-L861C11) to automatically create grafana dashboard(s) for the above monitoring.

**Comment by Pothulapati** [comment]
This is a valid feature request @ionfury! Don't have a timeline for it yet but might work on it next week! Meanwhile, feel free to raise a PR if you want/can!

**Comment by hermanbanken** [comment]
Plus one here too. We use DataDog with OpenMetrics so this means that the Pod instance that runs DragonflyDB should have certain DataDog-specific annotations:

```
    annotations:
      ad.datadoghq.com/mycontainer-dragonfly.check_names: '["openmetrics"]'
      ad.datadoghq.com/mycontainer-dragonfly.init_configs: '[{}]'
      ad.datadoghq.com/mycontainer-dragonfly.instances: '[{
          "prometheus_url": "http://%%host%%:6379/metrics",
          "namespace": "dragonflydb",
          "metrics": ["*"]
          }]'
```

**Comment by Pothulapati** [comment]
Ah, We can have a way to pass annotations into the Dragonfly pod! This shouldn't be hard. Just adding an `annotations` field into the CRD and passing that into the Statefulset spec.

**Comment by hermanbanken** [comment]
@Pothulapati that would be great!

**Comment by Pothulapati** [comment]
Fixed with https://github.com/dragonflydb/dragonfly-operator/pull/101 https://github.com/dragonflydb/dragonfly-operator/pull/113
