### ISSUE TITLE
Support configuring storage and snapshots

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly-operator#75]
Request form discord user (rmenr)

**Comment by cecchigl** [comment]
I'm trying to add persistent storage to statefulsets created bye the operator, adding pvc and volume mounts on /data.
Can I ask you if this is safe ? Will these configuration be overwritten somehow by the operator ?

**Comment by ksingh-scogo** [comment]
@cecchigl  very much interested in this feature , happy to be a test user and contribute in testing this

**Comment by tekumara** [comment]
See https://www.dragonflydb.io/docs/managing-dragonfly/operator/snapshot-pvc and https://www.dragonflydb.io/docs/managing-dragonfly/operator/snapshot-s3

**Comment by Pothulapati** [comment]
Closing this, as this is now fixed! Thanks @tekumara for the references.
