### ISSUE TITLE
Support for nodeSelector and also custom pod labels and annotations

### ISSUE THREAD

**Issue by jim12321** [dragonflydb/dragonfly-operator#80]
Would love if this supported defining nodeSelector (not using the affinity method).

Also to have custom pod labels and annotations.

Thanks.

**Comment by Pothulapati** [comment]
Hey @jim12321,

A valid request for direct node selectors, instead of affinities!

**Comment by jim12321** [comment]
Cool.  Thanks for the link.  Would love to use but want to wait for node selector support.  :D

**Comment by scog** [comment]
> Cool. Thanks for the link. Would love to use but want to wait for node selector support. :D

Same. Would be great to have `nodeSelector` support implemented!

**Comment by Pothulapati** [comment]
Considering that nodeAffinity can do the same task, Adding `nodeSelector` is not a priority but feel free to raise a PR and we are more than happy to help you get it merged!
