### ISSUE TITLE
Feature Request : Dragonfly-operator to support TLS Deployment of dragonfly

### ISSUE THREAD

**Issue by ksingh-scogo** [dragonflydb/dragonfly-operator#85]
If you deploy Dragonfly over an endpoint that's connected to the internet, you probably need to protect your data from leaking or being intercepted. In order to support that, dragonfly can serve your data over TLS.

Dragonfly-Operator should have a mechanism to supply TLS certs to dragonfly and start dragonfly with TLS 

```
$ sudo ./dragonfly \
  --tls \
  --tls_key_file=/etc/letsencrypt/live/dfly.scalable-meteorite-collections.com/privkey.pem \
  --tls_cert_file=/etc/letsencrypt/live/dfly.scalable-meteorite-collections.com/fullchain.pem
```

Once dragonfly is started with TLS key and certs , redis client can use the certs to establish a TLS connection.

**Comment by Abhra303** [comment]
Hi @ksingh-scogo, thanks for opening an issue. We have TLS in our roadmap. So you will soon be able to use it with our operator :)

**Comment by tekumara** [comment]
See https://www.dragonflydb.io/docs/managing-dragonfly/operator/server-tls
