### ISSUE TITLE
Support for ARM architecture

### ISSUE THREAD

**Issue by monlor** [dragonflydb/dragonfly-operator#86]
Please consider adding support for the ARM architecture to enable usage on ARM-based server. Thank you!

**Comment by DarkmatterVale** [comment]
+1 this comment, would like to run Dragonfly on a Kubernetes cluster with ARM nodes.

Not sure if this is too much work, given that it's already possible to run DragonflyDB itself on an ARM host.

**Comment by Pothulapati** [comment]
@DarkmatterVale You are right, and it isn't too much work. Considering that we already have a PR for this, You can expect this to be available in the coming days!

**Comment by Pothulapati** [comment]
Closing as this is fixed #126
