### ISSUE TITLE
关于Mysql和Redis的使用的一些疑问

### ISSUE THREAD

**Issue by wangqu123456** [dragonflydb/dragonfly-operator#95]
在K8s集群中部署时使用内部Mysql和Redis时，会起相关的statefulset，我看代码中用到这两个组件的地方主要是控制台的rest服务，以及角色管理；实际一次P2P下载任务涉及到的数据是不是都不会跟这两个组件有联系。

**Comment by Pothulapati** [comment]
Closing this as this repository is about the Operator for [Dragonfly](https://www.dragonflydb.io/) i.e In Memory cache database and not the image registry p2p caching.

Feel free to reopen if the issue is about it.
